### ISSUE TITLE
Link the docs in the readme

### ISSUE THREAD

**Issue by MrFellox** [DisnakeCommunity/disnake-ext-components#11]
### Summary

Add the documentation as a hyperlink in the readme

### What is the feature request for?

The documentation

### The Problem

None

### The Ideal Solution

First of all, I'm talking about this documentation page: https://disnake-ext-components.readthedocs.io/en/docs/
This could be done in many ways but the most simple one would be to add it as a hyperlink like so:

# disnake-ext-components

An extension for disnake aimed at making component interactions with listeners somewhat less cumbersome.
Requires disnake version 2.5.0 or above.

[Documentation](https://disnake-ext-components.readthedocs.io/en/docs/)

**Comment by Chromosomologist** [comment]
This will be done as part of #6. The docs currently are not listed in the readme because they are not yet finished.
